# Create aliases
alias ls='ls --color=always';
alias tree='tree -C';
alias nano='nano --smooth --tabsize=4 --autoindent';
alias python3='python';
alias pip3='pip';
alias diff='colordiff';
alias cdiff='cdiff --side-by-side --width=0';
alias grep='grep --color=always';
alias ping='prettyping --nolegend';
alias make='colormake';
alias clock='tty-clock -sctD -C 7';
alias rand='python $HOME/.scripts/rand.py';
alias midi='fluidsynth -a alsa -m alsa_seq -l -i /usr/share/soundfonts/FluidR3_GM2-2.sf2';
alias sizeof='du -hsx';
alias lsupdates='python $HOME/.scripts/lsupdates.py';
alias cleanhistory='python $HOME/.scripts/cleanhistory.py';
alias watchlist='bash $HOME/documents/personal/local/arch-linux/watchlist/watchlist.sh';
alias dark-left='xrandr --output GPU-0.HDMI-0 --brightness 0.2';
alias light-left='xrandr --output GPU-0.HDMI-0 --brightness 1.0';
alias dark-right='xrandr --output GPU-1.HDMI-0 --brightness 0.2';
alias light-right='xrandr --output GPU-1.HDMI-0 --brightness 1.0';
alias package-sync='python $HOME/.scripts/package_sync.py';
