# Additional incudes
includes=/etc/X11/xinit/xinitrc.d;
if [ -d "$includes" ];
then
    for f in "$includes/"*;
    do
        [ -x "$f" ] && . "$f";
    done
    unset f;
fi;
unset includes;

# Read  Xresources if it hasn't already been read
[[ -f ~/.Xresources ]] && xrdb -merge ~/.Xresources;

# Mute the PC Speaker (aka buzzer)
xset -b;
# Start XFCE session
exec startxfce4;

